### ISSUE TITLE
Use of `from now` carries vague implication of future tense

### ISSUE THREAD

**Issue by myii** [github/time-elements#101]
Had a situation on [this PR](https://github.com/saltstack-formulas/template-formula/pull/48).  As I filled in the comment, I saw:

```
myii requested review from aboe76 and noelmcloughlin 3 minutes from now
```

To be fair, this soon became:

```
myii requested review from aboe76 and noelmcloughlin 4 minutes ago
```

So probably just a glitch.  Just to be clear, `from now` connotes a future event, as mentioned [on this page](https://www.ldoceonline.com/dictionary/future).

**Comment by dgraham** [comment]
This is caused by a difference in clock time on the client and server.
