### ISSUE TITLE
Mixed languages in '<relative-time>'

### ISSUE THREAD

**Issue by DominikPalo** [github/time-elements#111]
Issues lists on GitHub have relative times displayed in two languages. For example, my os/browser is set to the Slovak language and when I open a GitHub issues list, some relative times are displayed as translated (red) and some in English (blue) - see the attached screenshot.

Browser: Google Chrome 74.0.3729.169
OS: macOS Mojave 10.14.4 

<img width="485" alt="github" src="https://user-images.githubusercontent.com/1623257/58759628-5c4bba00-852d-11e9-8e4a-ac9b37f8e162.png">

**Comment by Faierbel** [comment]
The same problem occurs with me. Part of it is in Polish, in part in English.
![Annotation 2019-06-02 134839](https://user-images.githubusercontent.com/25534725/58760829-68d80e80-853d-11e9-9ace-2ec20b3d9b06.png)

**Comment by koddsson** [comment]
Hey @DominikPalo and @Faierbel 👋

I'm unable to reproduce this on my machine. Would you happen to have any Chrome extensions installed that could be causing this? Is this reproducible in Incognito Mode (or with extensions disabled).

**Comment by koddsson** [comment]
Hey @DominikPalo and @Faierbel 👋

I'm unable to reproduce this on my machine. Would you happen to have any Chrome extensions installed that could be causing this? Is this reproducible in Incognito Mode (or with extensions disabled).

**Comment by khellang** [comment]
I saw this 2 minutes ago as well (mix between Norwegian and English, didn't capture screenshot), but I'm unable to repro anymore 🤔 😕

**Comment by DominikPalo** [comment]
I've just tried and it happens also in Incognito mode (with all Chrome extensions disabled). But I have to switch to the "Closed" tab and then back to the "Open" tab to replicate it - see the recording: https://gyazo.com/126ce5a0351f06af12f03d7116d69622

**Comment by khellang** [comment]
Managed to reproduce after a few refreshes on pulls, but not on issues:

![image](https://user-images.githubusercontent.com/582487/58799096-a18eeb00-8604-11e9-96ae-2095575da26b.png)

**Comment by khellang** [comment]
BTW, I have `lang="en"` on the `html` tag, `Accept-Language: en,nb;q=0.9` and `navigator.language === "en"` 🤷‍♂

**Comment by koddsson** [comment]
I've figured out what is going on with all your help and am able to reproduce this. I'll try to have a fix going out soon!

**Comment by koddsson** [comment]
We've downgraded the package on github.com until we fix the issue in `github/time-elements` so you should be seeing only english relative timestamps again. I'll keep this issue open until we've shipped a fix to the package.
