### ISSUE TITLE
time-until wrong calculation

### ISSUE THREAD

**Issue by rnons** [github/time-elements#134]
Today is `Jan 18, 2020`,

but `<time-until datetime="2020-12-31T00:00:00"></time-until>` outputs `next year`

![image](https://user-images.githubusercontent.com/1082650/72660025-47179300-3a0b-11ea-90e0-b1ad52c379cc.png)

**Comment by muan** [comment]
1. The timestamp you used does not have a timezone specified, so the time diff would be your local time ~ 2020/12/31T00:00:00 UTC, which can be further away.
2. The relative time calculation is rounded [here](https://github.com/github/time-elements/blob/ad7c3be2b3bf602daedd26acc4f3c4bf84e8fe87/src/relative-time.js#L122) so a 11.5 month rounds up to 12 months away, which is displayed as next year [here](https://github.com/github/time-elements/blob/ad7c3be2b3bf602daedd26acc4f3c4bf84e8fe87/src/relative-time.js#L127).
3. If you wishes to see a more specific `<time-until>` (aka one that is not loosely rounded), use [`format="micro"`](https://github.com/github/time-elements#micro-format), which will give you the exact days until the date.
