### ISSUE TITLE
Lost in an empty sea

### ISSUE THREAD

**Issue by pedro2555** [github/time-elements#136]
# How does one use this?

I'm using Polymer 2 (and I will upgrade, in due time). And bower (npm, another day, when its quicker).

All attempts I've done, I just cannot import any component this projects claims to add.

## How to install this?
Does `bower install <git_repo>` do the thing? Do I need to install using `npm`, really?

## How to import
Installing with bower, adds a bunch of `.js` files. Where, how, and which files should I import?

Which file to import? Link or Script tag?

**Comment by koddsson** [comment]
> Does `bower install <git_repo>` do the thing?

No. We don't publish to bower.

> Do I need to install using `npm`, really?

Yes. You can find the installation instructions in [the README](https://github.com/github/time-elements#installation).

**Comment by pedro2555** [comment]
Ok. Thanks for the clarification. Still I'm unable to add this to my project. I would argue the README could be clearer in that regard.

The web components don't seem to be loaded properly, I always get the plain text content inserted into the element.

**Comment by pedro2555** [comment]
If you can clarify my second part, I will send an update to the README.
