### ISSUE TITLE
relative-time and time-ago elements display date after relative string

### ISSUE THREAD

**Issue by bmarkons** [github/time-elements#137]
Hi,

When the page loads temporarily I can see the absolute time next to relative. This happens for both relative-time and time-ago elements.

![Screen Shot 2020-05-14 at 6 08 42 PM](https://user-images.githubusercontent.com/9396752/81958571-78e1e480-960e-11ea-91a3-6af4dbba27b4.png)

Are you maybe familiar with this issue?

One second after the page is loaded the element displays as it should - only the relative time.

Thank you :)

**Comment by dgraham** [comment]
The elements [overwrite textContent](https://github.com/github/time-elements/search?q=textContent+%3D&unscoped_q=textContent+%3D) rather than append to it, so you might start debugging at those assignments to see what content is inserted.

**Comment by bmarkons** [comment]
Actually we figured this out by moving `require("time-elements")` from the head section to the bottom of the body tag.

Thank you!
