### ISSUE TITLE
time-elements not translated in Safari/iPhone

### ISSUE THREAD

**Issue by globalistas** [github/time-elements#140]
In my project, the following issue is manifested with time-elements, but only in Safari. I am installing time-elements via 'npm install' on Debian 10 and it seems to install v3.0.0 (attached package.json), so maybe I need to upgrade somehow?

https://github.com/globalistas/ceknito/issues/24

**Comment by globalistas** [comment]
Update: I upgraded to v3.1.1 but it didn't resolve the issue.

**Comment by koddsson** [comment]
@globalistas I just checked on cekni.to on my iPhone and it works correctly for me. Are you still having issues?

**Comment by globalistas** [comment]
> @globalistas I just checked on cekni.to on my iPhone and it works correctly for me. Are you still having issues?

Hmm it does? Can you maybe post a screenshot from your phone?

**Comment by koddsson** [comment]
What version of iOS and Safari are you running?

![3DEEB08E-5EBE-467A-A8F3-EB8B98AE6B59_1_105_c](https://user-images.githubusercontent.com/318208/93769310-25118880-fc0a-11ea-9506-f37063bb4c47.jpeg)

**Comment by globalistas** [comment]
Well that's quite unecepected! I'm running iOs 13.6.1 on my iphone SE (older generation), with English (UK) language set in the phone preferences.

This is the browser info from Safari:
iPhone; CPU iPhone OS 13_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1

And I've had a friend of mine check on his Mac with Safari and he saw time-elements in English as well...

Weird, but maybe this will be enough info to troubleshoot?

**Comment by globalistas** [comment]
The issue seems to be gone after installing iOS 14.
