### ISSUE TITLE
The time zone handling appears sporadically broken

### ISSUE THREAD

**Issue by hankeliu2015** [github/time-elements#146]
Hi, we have an issue on the time zone handling. Details under <Time zone display can be wonky GUI/covid-vaccine-spotter#49>, screenshots also attached. Anybody can help take a look? Thanks, Hank

**Comment by koddsson** [comment]
I don't understand the issue. Could you elaborate on it and attach a minimal reproducible example?

**Comment by hankeliu2015** [comment]
It sometimes works, but after refreshes, I can usually get some of the times on the page to end up being in EST instead of MST. thanks!
https://user-images.githubusercontent.com/16155615/112313455-3d786380-8c7e-11eb-9e7b-7ef531cb1911.mov

**Comment by hankeliu2015** [comment]
https://user-images.githubusercontent.com/16155615/112313601-6b5da800-8c7e-11eb-8fab-9c0009d1a683.mov

**Comment by keithamus** [comment]
This looks like a FOC - how is the component loaded? Do you have it dynamically imported, or perhaps in a `deferred` script tag within a large bundle? The time is updated when the JS kicks in.

**Comment by hankeliu2015** [comment]
> This looks like a FOC - how is the component loaded? Do you have it dynamically imported, or perhaps in a `deferred` script tag within a large bundle? The time is updated when the JS kicks in.

Hi @keithamus , still waiting for the project founder to reply. thanks!
![Screen Shot 2021-03-24 at 8 06 18 PM](https://user-images.githubusercontent.com/16155615/112399337-6fb8ae00-8cdc-11eb-8b4a-f5f0c34d914e.png)

@MoralCode, any ideas? Nick has not replied yet. I believe he made some adjustment on local-time component, not a standard npm install. Did not found time-element in dependencies.

**Comment by MoralCode** [comment]
I havent done a deep-dive into this or how vaccinespotter implements it, but from my video posted on the vaccinespotter repo i suspect this issue is related to #135 (and is probably a duplicate, although this prob needs a second opinion).

Essentially when the page is reloaded, the time will briefly be displayed (presumably) literally as it appears within the `<local-time>` tag from the `{{timeLocale}}` variable that i suspect (again havent done a deep dive) is coming from Vue itself or some external source.

I also agree with @keithamus in that it could just be a slow js issue. In this case, and if this library supports it, the solution may be to just remove the time from within the `<local-time>` tag or add some setting to make it not render anything until the js "kicks in" with the real, adjusted time. This way it appears to users as just loading with the correct time, rather than displaying the wrong time for a fraction of a second and correcting itself. This is also what i think is intended by #135.

**Comment by hankeliu2015** [comment]
Thanks @MoralCode! I thought opening a new ticket helps getting the attention :-) 
Did some test, the {{timeLocale}}'s purpose seems to provide a format for rending local time. When I replace it with a simple 'dot' in there, the local time rendered as normal, just a flash on the 'dot'. See my video clip. 

https://user-images.githubusercontent.com/16155615/112410257-4a826a80-8cf1-11eb-9a55-00757542cf6f.mov

**Comment by MoralCode** [comment]
@hankeliu2015 perfect! Will it let you not put anything at all in between the tags?

**Comment by hankeliu2015** [comment]
> anything

I wished it would be that simple :-) Here is what happened if i left it nothing or a space. 

" ERROR  Failed to compile with 1 errors                                                                                                         friendly-errors 23:45:01


 ERROR  ESLintError                                                                                                                             friendly-errors 23:45:01

                                                                                                                                                friendly-errors 23:45:01
/Users/liuh/Development/m6-opensource/covid-vaccine-spotter/website/components/DisplayLocalTime.vue
  12:7  error  Replace `··>·</local-time⏎······` with `>⏎······</local-time`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option."

**Comment by hankeliu2015** [comment]
@keithamus @moralCode , here is my understanding how the local-time component worked. It got props(time and time-zone) from its parent component Store.vue, which has its own parent State.vue passing props(store). store data is fetched form a local _state.json file under dev environment. In production, store data is fetched from APIs(scrapping data from multi sites). I am still not sure how Nick 'imported' the local-elements into a Vue template. <https://github.com/GUI/covid-vaccine-spotter/blob/main/website/components/DisplayLocalTime.vue> . Thanks!

**Comment by hankeliu2015** [comment]
@keithamus, Our project founder decided to skip the server-side rendering and just letting Vue handle the rendering. I am closing this issue for now. Thanks!
