### ISSUE TITLE
Make "ago" optional for time-ago

### ISSUE THREAD

**Issue by antonmoiseev** [github/time-elements#39]
What do you think about making "ago" optional for `time-ago`? It's often useful to get a human-readable time span and combine it with custom suffix, e.g.: `2 days since the last meeting`, `10 years of experience`. moment.js supports [similar feature](http://momentjs.com/docs/#/displaying/fromnow/) via a boolean argument to `fromNow(true)` method.

**Comment by Sharky1231** [comment]
How often does `<time-ago>` refreshes? Because I see `just now` and then randomly later `36 seconds ago`

**Comment by josh** [comment]
Hey all! The direction we're planning to take here is to lean on the new `Intl.RelativeTimeFormat` API for internationalization https://github.com/github/time-elements/pull/104. Thanks!
