### ISSUE TITLE
HTML Import 

### ISSUE THREAD

**Issue by BLamy** [github/time-elements#57]
Any way you guys can make a time-elements.html file which simply imports the javascript file. 

This is the proper way to import web components because importing an html file twice does nothing while importing a javascript file twice will try to run the code twice. 

TLDR: 
Add a file named: **time-elements.html**
the contents of that file should be exactly
`<script src="./time-elements.js"></script>`

**Comment by dgraham** [comment]
The JavaScript file should be bundled and served a single time by the application. HTML imports isn't something we're interested in right now.

**Comment by BLamy** [comment]
Care to explain why? It's part of the *big 4* web-component standards. Even with browsers like firefox taking an opinion against them they are going to be widely used and polyfilled until es6 modules can be adopted and even then they will still be used. 

It's one file that you add to your repo that will never be changed, and you have future proofed for an emerging standard. What you are suggesting is completely against the web components philosophy. I shouldn't have to know about the internal implementation of my installed components to use them.

**Comment by morficus** [comment]
+1 for this.
No one using custom elements will ever expect to include a .js file and the README file doesn't mention anything about it either... so at the very least it would be nice to have it document.

**Comment by TomK** [comment]
+1 here also.  If you import multiple elements which include this script you will get errors regarding registering the time elements twice.   It's anti-pattern to have the app include the script.
