### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by shield-9** [github/time-elements#58]
If this element supports translation, it would be great!

Example:
`<time datetime="2015-02-23T09:51:57Z" is="relative-time" lang="ja-jp">Feb 23, 2015</time>`

**Comment by nickbuddendotcom** [comment]
Our team would be willing to put together a PR on this. @josh @dgraham any preference on how this gets implemented?

**Comment by chemerisuk** [comment]
@shield-9 @nickbuddendotcom I have a separate project https://github.com/chemerisuk/better-time-element that solves similar problem and has an ability to translate displayed values. It does not rely on custom element polyfills though but uses different tricks to work on future elements as well. At present it supports only `time[is=local-time]` but I'm planning to add more custom elements soon.

**Comment by ZakharDay** [comment]
Hi everyone! I'm trying to add l16n to this package and have some difficulties. https://github.com/ZakharDay/time-elements/tree/l16n

1. Most tests are failing and I can't resolve the issue. Two biggest problems that I can't figure out:

```
constructor create local-time from constructor:
undefined is not a constructor (evaluating 'new window.LocalTimeElement()')

constructor create relative-time from constructor:
undefined is not a constructor (evaluating 'new window.RelativeTimeElement()')
```

2. Next strange thing is when I clone my fork, change branch to l16n and then run ```make``` everything is great. But if I do ```npm install``` with link to my GitHub tarball this next two things happen.

2.1 In app where I use this package as dependency I see:

```
Module not found: Error: Cannot resolve module 'time-elements'
```

I fount that it's because I've installed it not from npm but from GitHub.

2.2 I tried to run ```make``` in ```node_modules/time-elements``` folder in my project and got this:

```
node_modules/.bin/rollup -c
node_modules/.bin/rollup -c rollup.legacy-config.js
Error transforming /Users/zakharday/@_Dev/C/Cerebro/client/node_modules/time-elements/src/index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error transforming /Users/zakharday/@_Dev/C/Cerebro/client/node_modules/time-elements/src/index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/Users/zakharday/@_Dev/C/Cerebro/client/node_modules/time-elements/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:46:104)
    at Object.transform$1 [as transform] (/Users/zakharday/@_Dev/C/Cerebro/client/node_modules/time-elements/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:117:18)
    at /Users/zakharday/@_Dev/C/Cerebro/client/node_modules/time-elements/node_modules/rollup/src/utils/transform.js:19:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
make: *** [build] Error 1
```

I'll be glad for any help.

**Comment by josh** [comment]
Hey all! The direction we're planning to take here is to lean on the new `Intl.RelativeTimeFormat` API for internationalization https://github.com/github/time-elements/pull/104. Thanks!
