### ISSUE TITLE
Avoid is="" API

### ISSUE THREAD

**Issue by josh** [github/time-elements#60]
Safari 10 will be supporting Custom Elements soon, but won't support `is=""`.

We should rewrite this extension without extending `<time>` and just do `<relative-time>` and `<local-time>`.

Hopefully we can get github.com updated long before so future Enterprise versions will be ready with this change. Unsure if the Polymer Custom Element polyfill will correctly cover a partial Custom Elements implementation.

-
To: @dgraham @mislav 
CC: @notwaldorf @github/js

**Comment by mislav** [comment]
Thanks for the heads-up… that's good to know! Partial feature implementations are scary :see_no_evil:
