### ISSUE TITLE
Compatibility broken with Web components 1.0.0

### ISSUE THREAD

**Issue by lpellegr** [github/time-elements#84]
When used in Firefox, I get the following error:

> TypeError: document.registerElement is not a function

![screenshot from 2017-06-27 11-16-56](https://user-images.githubusercontent.com/128898/27581002-acb61f6c-5b2c-11e7-89ee-62c341f2a4d0.png)

The polyfill with version 1.0.0 of web component assumes that `window.customElements.define` is used.

**Comment by lpellegr** [comment]
Related to https://github.com/github/time-elements/pull/67.

**Comment by muan** [comment]
v1.0.0 is out now with Custom Elements v1 API. [A polyfill example can be found here](https://github.com/github/time-elements/blob/master/examples/polymer.html).
