### ISSUE TITLE
tell how to properly import this into other webcomponents

### ISSUE THREAD

**Issue by ensonic** [github/time-elements#85]
Somewhat related to #81. Right now polymer lint will complain
```
 warning [undefined-elements] - The element relative-time is not defined
```
If I just have this at the end of modules:
```
 ...
 <script src="../bower_components/time-elements/time-elements.js"></script>
</dom-module>
```

**Comment by drigz** [comment]
Looks like this is because the linter doesn't support the deprecated v0 API: Polymer/polymer-linter#63 
However, this PR to switch to v1 seems stalled: github/time-elements#67

**Comment by muan** [comment]
v1.0.0 is out now with Custom Elements v1 API. [A polyfill example can be found here](https://github.com/github/time-elements/blob/master/examples/polymer.html).
